openapi: 3.0.0
info:
  title: Linkup API Docs
  version: 1.0.0
  description: API for Linkup project.
  contact:
    name: Linkup Team
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Logs in a user (Local)
      description: >
        Authenticates a user using email and password. On successful authentication, a JWT token is generated,
        set as an HTTP-only cookie, and user details are returned.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "valid_password"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successful"
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "unique_user_id"
                      email:
                        type: string
                        example: "user@example.com"
        '400':
          description: Email and password are required
        '401':
          description: Invalid credentials
        '500':
          description: Server error

  /auth/logout:
    get:
      tags:
        - Auth
      summary: Logs out a user (Local)
      description: >
        Clears the JWT cookie to log out the user.
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logout successful"

  /auth/google:
    get:
      tags:
        - Google Auth
      summary: Initiates Google authentication
      description: >
        Redirects the user to Google to initiate OAuth2 authentication.
      responses:
        '302':
          description: Redirects to Google for authentication.

  /auth/google/callback:
    get:
      tags:
        - Google Auth
      summary: Google OAuth callback
      description: >
        Handles the callback from Google OAuth. On successful authentication, a JWT token is issued,
        set as an HTTP-only cookie, and user details are returned.
      responses:
        '200':
          description: Google authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Google authentication successful"
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "unique_user_id"
                      email:
                        type: string
                        example: "user@example.com"
                  tokens:
                    type: object
                    description: Google tokens stored in session (if applicable)
        '401':
          description: Google authentication failed
        '500':
          description: Server error

  /auth/google/logout:
    get:
      tags:
        - Google Auth
      summary: Logs out a Google authenticated user
      description: >
        Revokes the Google access token (if applicable), destroys the session, and clears the JWT cookie.
      responses:
        '200':
          description: Google logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Google logout successful"
        '500':
          description: Server error

  /api/v1/user/send-otp:
    post:
      tags:
        - OTP
      summary: Generate and send OTP
      description: >
        Generates a one-time password (OTP) and sends it to the user's email.
        The OTP is stored in the session and expires in 10 minutes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: "test@example.com"
      responses:
        '200':
          description: OTP has been sent to your email.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "OTP has been sent to your email"
        '400':
          description: Email is required.
        '500':
          description: Server error

  /api/v1/user/verify-otp:
    post:
      tags:
        - OTP
      summary: Verify OTP
      description: >
        Verifies the one-time password (OTP) provided by the user.
        If the OTP is valid and not expired, the session values are cleared and a success message is returned.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
              properties:
                otp:
                  type: string
                  example: "123456"
                token:
                  type: string
                  example: "jwt_token"
      responses:
        '200':
          description: OTP verified successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "OTP verified successfully"
        '400':
          description: OTP is required.
        '401':
          description: Invalid OTP or OTP expired.
        '500':
          description: Server error

  /api/v1/user/verify-email:
    post:
      tags:
        - Auth
      summary: Verify Email Availability
      description: >
        Checks if the provided email is available (i.e., not already in use).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: "user@example.com"
      responses:
        '200':
          description: Email is available.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email is available"
        '400':
          description: Email already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email already exists"
        '500':
          description: Server error

  /api/v1/user/signup/starter:
    post:
      tags:
        - Auth
      summary: Register a New User (Starter)
      description: >
        Registers a new user by creating an account with the provided starter information.
        Required fields include firstName, lastName, email, password, and OTP for verification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - password
                - otp
              properties:
                firstName:
                  type: string
                  example: "John"
                lastName:
                  type: string
                  example: "Doe"
                email:
                  type: string
                  example: "john.doe@example.com"
                password:
                  type: string
                  example: "securepassword"
                otp:
                  type: string
                  example: "123456"
                country:
                  type: string
                  example: "USA"
                city:
                  type: string
                  example: "New York"
                isStudent:
                  type: boolean
                  example: false
                jobTitle:
                  type: string
                  example: "Software Engineer"
                school:
                  type: string
                  example: "MIT"
                schoolStartYear:
                  type: number
                  example: 2015
                schoolEndYear:
                  type: number
                  example: 2019
                is16OrAbove:
                  type: boolean
                  example: true
                employmentType:
                  type: string
                  example: "Full-time"
                recentCompany:
                  type: string
                  example: "Google"
      responses:
        '201':
          description: Signup successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Signup successful"
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                        example: "john.doe@example.com"
        '400':
          description: Required fields missing or invalid OTP.
        '409':
          description: User already exists.
        '500':
          description: Server error

  /api/v1/user/forget-password:
    post:
      tags:
        - Auth
      summary: Request password reset
      description: >
        Sends a password reset link to the user's email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: "user@example.com"
      responses:
        '200':
          description: Password reset link sent.
        '400':
          description: Invalid email format.
        '404':
          description: Email not registered.
        '500':
          description: Server error

  /api/v1/user/reset-password:
    post:
      tags:
        - Auth
      summary: Reset password
      description: >
        Resets the user's password using the provided token and new password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
                - token
              properties:
                password:
                  type: string
                  example: "new_secure_password"
                token:
                  type: string
                  example: "jwt_token"
      responses:
        '200':
          description: Password reset successful.
        '400':
          description: Invalid request.
        '401':
          description: Invalid or expired token.
        '404':
          description: User not found.
        '500':
          description: Server error

  /api/v1/user/update-password:
    post:
      tags:
        - Auth
      summary: Update password
      description: >
        Updates the user's password using the provided old password, new password, and token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - old_password
                - new_password
              properties:
                old_password:
                  type: string
                  example: "old_password"
                new_password:
                  type: string
                  example: "new_secure_password"
                token:
                  type: string
                  example: "jwt_token"
      responses:
        '200':
          description: Password updated successfully.
        '400':
          description: Invalid request.
        '401':
          description: Invalid or expired token.
        '403':
          description: Old password is incorrect.
        '404':
          description: User not found.
        '500':
          description: Server error
