# Swagger Documentation
# This is the API documentation for the API Gateway

swagger: '2.0'
info:
  title: Linkup API Documentation
  description: Linkup API Gateway 
  version: 1.0.0
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: User
    description: User operations
  - name: Admin
    description: Admin operations
  - name: Posts
    description: Posts operations
  - name: Notification
    description: Notification operations
  - name: Chat
    description: Chat operations
  - name: Auth
    description: Authentication(Signup/Signin and Login/Logout) operations
